---
title: "Homework 02"
author: "Konrat Pekkip"
output: github_document
---

```{r load-packages, message = FALSE, include = FALSE}
#load required packages
library(tidyverse)
library(fs)
library(ggridges)
library(dsbox)
```

1.  **A new day, a new plot, a new geom.**

```{r exercise-1}
ex1 <- edibnb %>%
  mutate(median_review = fct_reorder(neighbourhood, review_scores_rating, median, na.rm = TRUE))




ex1 %>%
  ggplot(data = subset(., !is.na(neighbourhood)),
         mapping = aes(x = median_review,
                       y = neighbourhood))+
  geom_density_ridges(na.rm = TRUE,
                      quantile_lines=TRUE,
                      quantile_fun=function(x,...)median(x))


```

2.  **Key lyme pie.**

```{r label-me-2}

```

3.  **Foreign Connected PACs.**

```{r load-pac-data}
# get a list of files with "Foreign Connected PAC" in their names
list_of_files <- dir_ls(path = "data", regexp = "Foreign Connected PAC")

# read all files and row bind them
# keeping track of the file name in a new column called year
pac <- read_csv(list_of_files, id = "year")
```


4.  **Hop on.**

